version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: modsen_db
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: admin
    volumes:
      - .:/var/lib/postgresql
    ports:
      - '5432:5432'
    networks:
      - event-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pdfmain.user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password123
    volumes:
      - .:/var/lib/pgadmin/
    ports:
      - "5050:80"
    networks:
      - event-network
    restart: unless-stopped

  event-service:
    depends_on:
      - postgres
      - pgadmin
    image: modsen/event-service:0.0.1-SNAPSHOT
    ports:
      - '8080:8080'
    networks:
      - event-network

networks:
  event-network: