CREATE TABLE events(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject varchar(50) not null,
    description text not null,
    organizer varchar(30) not null,
    place varchar(30) not null,
    event_time timestamp not null,
    created_at timestamp not null
)